/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Type__1 = IDL.Record({
  'code' : IDL.Text,
  'gameId' : IDL.Nat,
  'effect' : IDL.Text,
  'category' : IDL.Text,
});
export const Type = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'genre' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const GeneratedCode = IDL.Record({
  'code' : IDL.Text,
  'userId' : IDL.Principal,
  'generatedAt' : Timestamp,
  'gameId' : IDL.Nat,
  'effect' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserGame = IDL.Record({
  'userId' : IDL.Principal,
  'gameId' : IDL.Nat,
  'addedAt' : Timestamp,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCheatCode' : IDL.Func([Type__1], [IDL.Nat], []),
  'addGame' : IDL.Func([Type], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateRandomCode' : IDL.Func([IDL.Nat], [GeneratedCode], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCheatCodeById' : IDL.Func([IDL.Nat], [Type__1], ['query']),
  'getCheatCodesForGame' : IDL.Func([IDL.Nat], [IDL.Vec(Type__1)], ['query']),
  'getGameById' : IDL.Func([IDL.Nat], [Type], ['query']),
  'getGeneratedCodesHistory' : IDL.Func(
      [],
      [IDL.Vec(GeneratedCode)],
      ['query'],
    ),
  'getUserLibrary' : IDL.Func([], [IDL.Vec(UserGame)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGameToLibrary' : IDL.Func([IDL.Nat], [], []),
  'searchGamesByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Type)], ['query']),
  'searchGamesByName' : IDL.Func([IDL.Text], [IDL.Vec(Type)], ['query']),
  'seedData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Type__1 = IDL.Record({
    'code' : IDL.Text,
    'gameId' : IDL.Nat,
    'effect' : IDL.Text,
    'category' : IDL.Text,
  });
  const Type = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'genre' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const GeneratedCode = IDL.Record({
    'code' : IDL.Text,
    'userId' : IDL.Principal,
    'generatedAt' : Timestamp,
    'gameId' : IDL.Nat,
    'effect' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserGame = IDL.Record({
    'userId' : IDL.Principal,
    'gameId' : IDL.Nat,
    'addedAt' : Timestamp,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCheatCode' : IDL.Func([Type__1], [IDL.Nat], []),
    'addGame' : IDL.Func([Type], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateRandomCode' : IDL.Func([IDL.Nat], [GeneratedCode], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCheatCodeById' : IDL.Func([IDL.Nat], [Type__1], ['query']),
    'getCheatCodesForGame' : IDL.Func([IDL.Nat], [IDL.Vec(Type__1)], ['query']),
    'getGameById' : IDL.Func([IDL.Nat], [Type], ['query']),
    'getGeneratedCodesHistory' : IDL.Func(
        [],
        [IDL.Vec(GeneratedCode)],
        ['query'],
      ),
    'getUserLibrary' : IDL.Func([], [IDL.Vec(UserGame)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGameToLibrary' : IDL.Func([IDL.Nat], [], []),
    'searchGamesByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Type)], ['query']),
    'searchGamesByName' : IDL.Func([IDL.Text], [IDL.Vec(Type)], ['query']),
    'seedData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };