/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GeneratedCode {
  'code' : string,
  'userId' : Principal,
  'generatedAt' : Timestamp,
  'gameId' : bigint,
  'effect' : string,
}
export type Timestamp = bigint;
export interface Type {
  'name' : string,
  'description' : string,
  'platform' : string,
  'genre' : string,
}
export interface Type__1 {
  'code' : string,
  'gameId' : bigint,
  'effect' : string,
  'category' : string,
}
export interface UserGame {
  'userId' : Principal,
  'gameId' : bigint,
  'addedAt' : Timestamp,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCheatCode' : ActorMethod<[Type__1], bigint>,
  'addGame' : ActorMethod<[Type], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateRandomCode' : ActorMethod<[bigint], GeneratedCode>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCheatCodeById' : ActorMethod<[bigint], Type__1>,
  'getCheatCodesForGame' : ActorMethod<[bigint], Array<Type__1>>,
  'getGameById' : ActorMethod<[bigint], Type>,
  'getGeneratedCodesHistory' : ActorMethod<[], Array<GeneratedCode>>,
  'getUserLibrary' : ActorMethod<[], Array<UserGame>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGameToLibrary' : ActorMethod<[bigint], undefined>,
  'searchGamesByGenre' : ActorMethod<[string], Array<Type>>,
  'searchGamesByName' : ActorMethod<[string], Array<Type>>,
  'seedData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];